# Generated by Django 5.1.15 on 2026-05-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaPrimaPiezaConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled_for_piezas", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "materia_prima",
                    models.OneToOneField(
                        db_column="materia_prima_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieza_config",
                        to="inventory.materiaprima",
                    ),
                ),
            ],
            options={
                "db_table": "materia_prima_pieza_config",
                "ordering": ["materia_prima_id"],
            },
        ),
    ]
